// <auto-generated />
namespace Com.HSJF.Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mortgage_Add_FourFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mortgage_Add_FourFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201608300627094_Mortgage_Add_FourFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
